import { readFileSync } from 'fs';
import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import type { Options as DocsOptions } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Archived doc versions, newest first. Written by `npm run docusaurus docs:version <x>`.
// Tolerates the file being absent or empty, which is the valid "no releases archived
// yet" state you land in after removing a version (see Versioning in README.md).
const DOC_VERSIONS: string[] = (() => {
  try {
    return JSON.parse(readFileSync('./versions.json', 'utf8'));
  } catch {
    return [];
  }
})();

// The newest archived version becomes the default served at /docs/. When nothing is
// archived this stays undefined, which Docusaurus reads as "current is the default",
// so /docs/ serves the in-development docs and /docs/dev/ is not generated.
const LAST_VERSION = DOC_VERSIONS[0];

// Pages pinned above the divider in their section's sidebar, in this order. Each list is
// filtered out of that section's autogenerated run by its own `sidebarItemsGenerator` below,
// then re-added explicitly in that section's sidebar file — sidebarsWhatsNew.js,
// sidebarsGuides.js, and sidebars.ts plus versioned_sidebars/*.json for the versioned docs.
// A page left in both places is listed twice, which is the bug these filters exist to prevent;
// a page filtered but never pinned disappears instead, which is the failure mode to watch for
// in the versioned section, where each version carries its own sidebar file.
const WHATS_NEW_PINNED = ['changelog', 'roadmap'];
const GUIDES_PINNED = ['getting-started'];
const DOCS_PINNED = ['index'];

// Plugins that existed under the old `/docs/**/plugins/<slug>/` URLs, used to redirect them to
// the flattened paths. This is a historical list, not a registry: a plugin added after the
// flatten never had such a URL and does not belong here. Renaming an existing slug does, or the
// shipped links for the old name stop resolving.
const PLUGIN_SLUGS = [
  'actor-pools',
  'blockout',
  'core',
  'dynamic-references',
  'guardian',
  'picker',
  'tooling',
  'ui',
  'world-assembly',
];

// Building every archived version on each hot reload gets slow as the archive grows,
// so in development we build only `current` plus the newest archive. Production is
// left undefined so a release build always contains the complete set. Filtering keeps
// this valid when there is nothing archived yet.
const DEV_ONLY_VERSIONS =
  process.env.NODE_ENV === 'development'
    ? ['current', LAST_VERSION].filter(Boolean)
    : undefined;

const config: Config = {
  title: 'NEXUS Framework',
  tagline: 'A battle-tested collection of game-ready plugins for Unreal Engine.',
  favicon: 'assets/favicon/favicon.ico',

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // Set the production url of your site here
  url: 'https://nexus-framework.com',
  // Set the /<baseUrl>/ pathname under which your site is served
  // For Cloudflare pages deployment, it is often '/<projectName>/'
  baseUrl: '/',
  trailingSlash: true,

  // Cloudflare pages deployment config.
  organizationName: 'dotBunny',
  projectName: 'NEXUS.Docs',
  onBrokenLinks: 'throw',


  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },
  themes: ['@docusaurus/theme-mermaid'],
  markdown: {
    mermaid: true
  },
  presets: [
    [
      'classic',
      {
        docs: {
          showLastUpdateTime: true,
          sidebarPath: './sidebars.ts',
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl:
            'https://github.com/dotBunny/NEXUS.Docs/tree/main/',

          // The newest released version, served at /docs/ as the default.
          // Bump this each time a new version is cut.
          lastVersion: LAST_VERSION,

          versions: {
            // Unreleased work on main, served at /docs/dev/.
            current: {
              label: 'main 🚧',
              path: 'dev',
            },
          },

          // Dev-only: build just the two newest versions so `npm run start` stays
          // fast as the archive grows. Derived from versions.json so it cannot go
          // stale, and always undefined in production so a release build is complete.
          onlyIncludeVersions: DEV_ONLY_VERSIONS,

          // Plugins stay autogenerated so a new one appears just by adding the folder.
          // Overview is pinned above the divider, so drop it here or it would be listed twice.
          //
          // This applies to EVERY version, and an archived version's sidebar is its own frozen
          // file under versioned_sidebars/. So a version whose sidebar is a bare autogenerated
          // block would lose Overview entirely rather than merely losing the divider — the pin
          // and this filter have to be added together. Both existing snapshots carry the pin,
          // and `docs:version` copies sidebars.ts forward, so future cuts inherit it.
          sidebarItemsGenerator: async ({ defaultSidebarItemsGenerator, ...args }) => {
            const items = await defaultSidebarItemsGenerator(args);
            return items.filter(
              (item) => !(item.type === 'doc' && DOCS_PINNED.includes(item.id)),
            );
          },
        },
        blog: false,
        theme: {
          customCss: [
            './src/css/base.css',
            './src/css/nav.css',
            './src/css/lander.css',
            './src/css/category.css',
            './src/css/type-details.css',
            './src/css/type-definitions.css',
            './src/css/plugin-details.css',
            './src/css/plugin-image-markup.css',
            './src/css/responsive.css'
          ]
        },
        gtag: {
          trackingID: 'G-988WNKTWNF',
          anonymizeIP: true
        }
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    colorMode: {
      defaultMode: 'dark',
      respectPrefersColorScheme: true,
      disableSwitch: false,
    },
    docs: {
      sidebar: {
        hideable: true
      },
    },
    mermaid: {
      theme: {
        light: 'neutral',
        dark: 'dark'
      },
      // options: { ... mermaid.js options }
    },

    // Replace with your project's social card
    image: 'assets/images/social/social-square.png',
    navbar: {
      title: 'EXUS Framework',
      logo: {
        alt: 'NEXUS Framework Logo',
        src: 'assets/svg/nexus.svg'
      },
      items: [
        {
          to: '/whats-new/changelog/',
          position: 'left',
          label: 'What\'s New',
          activeBaseRegex: `/whats-new/`
        },
        {
          type: 'docSidebar',
          sidebarId: 'docs',
          position: 'left',
          label: 'Docs'
        },
        {
          to: '/guides/getting-started/',
          position: 'left',
          label: 'Guides',
          activeBaseRegex: `/guides/`
        },
        {
          to: '/community/discord/',
          position: 'left',
          label: 'Community',
          activeBaseRegex: `/community/`
        },

        {
          type: 'docsVersionDropdown',
          position: 'right',
          dropdownActiveClassDisabled: true,
        },
        {
          href: 'https://github.com/dotBunny/NEXUS/issues/new/choose',
          label: 'Report Issue',
          position: 'right',
        },
        // Plugin dropdown. These use `type: 'doc'` rather than raw `to:` paths so a
        // reader browsing an older version (or /docs/dev/) stays inside that version
        // when they jump between plugins. docIds keep the trailing `/index`.
        {
          type: 'doc',
          docId: 'index',
          label: 'NEXUS Plugins',
          className: 'plugin-menu plugin-menu-base'
        },
        {
          type: 'doc',
          docId: 'core/index',
          label: 'Core',
          className: 'plugin-menu'
        },
        {
          type: 'doc',
          docId: 'actor-pools/index',
          label: 'Actor Pools',
          className: 'plugin-menu'
        },
        {
          type: 'doc',
          docId: 'blockout/index',
          label: 'Blockout',
          className: 'plugin-menu'
        },
        {
          type: 'doc',
          docId: 'dynamic-references/index',
          label: 'Dynamic References',
          className: 'plugin-menu'
        },
        {
          type: 'doc',
          docId: 'guardian/index',
          label: 'Guardian',
          className: 'plugin-menu'
        },
        {
          type: 'doc',
          docId: 'picker/index',
          label: 'Picker',
          className: 'plugin-menu'
        },
        {
          type: 'doc',
          docId: 'tooling/index',
          label: 'Tooling',
          className: 'plugin-menu'
        },
        {
          type: 'doc',
          docId: 'ui/index',
          label: 'User Interface',
          className: 'plugin-menu'
        },
        {
          type: 'doc',
          docId: 'world-assembly/index',
          label: 'World Assembly 🚧',
          className: 'plugin-menu'
        },
      ],
    },
    footer: {
      links: [
        {
          title: 'Docs',
          items: [
            {
              label: 'Getting Started',
              to: '/guides/getting-started/',
            },
            {
              label: 'Contributing',
              to: '/community/contributing/',
            },
            {
              label: 'Changelog',
              to: '/whats-new/changelog/',
            }
          ],
        },
        {
          title: 'GitHub',
          items: [
            {
              label: 'Milestones',
              href: 'https://github.com/dotBunny/NEXUS/milestones?sort=due_date&direction=asc'
            },
            {
              label: 'Roadmap',
              href: 'https://github.com/orgs/dotBunny/projects/6/views/2',
            },
            {
              label: 'Issues',
              href: 'https://github.com/orgs/dotBunny/projects/6/views/3',
            }
          ],
        },
        {
          title: 'Extras',
          items: [
            {
              to: 'https://discord.gg/2M9HczHanW',
              label: 'Discord',
            },
            {
              to: '/license',
              label: 'License',
            },
            {
              to: 'https://dotbunny.com/dethol/',
              label: 'DETHOL',
            },
          ],
        },
        {
          title: 'Static Analysis',
          items: [
            {
              html: '<a href="https://sonarcloud.io/summary/overall?id=dotBunny_NEXUS&branch=main"><img src="https://sonarcloud.io/api/project_badges/measure?project=dotBunny_NEXUS&metric=alert_status" alt="Quality Gate" /></a>',
            },
            {
              html: '<a href="https://sonarcloud.io/summary/overall?id=dotBunny_NEXUS&branch=main"><img src="https://sonarcloud.io/api/project_badges/measure?project=dotBunny_NEXUS&metric=code_smells" alt="Code Smells" /></a>',
            },
            {
              html: '<a href="https://sonarcloud.io/summary/overall?id=dotBunny_NEXUS&branch=main"><img src="https://sonarcloud.io/api/project_badges/measure?project=dotBunny_NEXUS&metric=sqale_rating" alt="Maintainability" /></a>',
            },
            {
              html: '<a href="https://sonarcloud.io/summary/new_code?id=dotBunny_NEXUS&branch=main"><img src="https://sonarcloud.io/api/project_badges/measure?project=dotBunny_NEXUS&metric=ncloc" alt="Lines Of Code" /></a>',
            }
          ]
        }
      ],
      copyright: `<a class="muted" href="https://dotbunny.com">&copy; dotBunny</a>`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
    algolia: {
      appId: 'D8GP244DEM',
      apiKey: 'bd75718f03cda407bf3d9fb59f637d96',
      indexName: 'nexus_framework_com_d8gp244dem_articles',
      // Required now that docs are versioned: scopes results to the version the
      // reader is currently browsing. With this false, a search from /docs/ would
      // return hits from /docs/dev/ and every archived version, mixed together.
      // NOTE: this only works once the Algolia crawler is emitting version facets
      // (docusaurus_tag / docusaurus_version) — that is configured at algolia.com,
      // not here. Until the index is re-crawled, results may look sparse.
      contextualSearch: true,
      searchPagePath: 'search',
    }
  } satisfies Preset.ThemeConfig,
  plugins: [
    // The `plugins/` path segment was dropped site-wide: `docs/plugins/<slug>/` became
    // `docs/<slug>/`, and both archived snapshots were flattened to match so the navbar's
    // `type: 'doc'` docIds resolve in every version. That changes URLs that have already
    // shipped and been indexed, so every old path is redirected to its new home. Driven off
    // PLUGIN_SLUGS rather than a bare regex so unrelated pages that merely start with a
    // matching word are left alone.
    [
      'client-redirects',
      {
        // Neither `whats-new/` nor `guides/` has an index page, so the bare route forwards to
        // the page that section opens on. Nothing in the site links to the bare paths — both
        // navbar items point straight at the target, because a client redirect is not a route
        // as far as `onBrokenLinks: 'throw'` is concerned and those links render on every page.
        // These entries are for anyone who types or has bookmarked the bare path.
        redirects: [
          { from: '/whats-new', to: '/whats-new/changelog' },
          { from: '/guides', to: '/guides/getting-started' },
        ],

        createRedirects(existingPath: string) {
          const match = existingPath.match(
            new RegExp(`^(/docs(?:/[^/]+)?)/(${PLUGIN_SLUGS.join('|')})(/.*)?$`),
          );
          if (!match) return undefined;
          const [, prefix, slug, rest = ''] = match;
          return [`${prefix}/plugins/${slug}${rest}`];
        },
      },
    ],
    function silenceMermaidUmdWarning() {
      return {
        name: 'silence-mermaid-umd-warning',
        configureWebpack() {
          return {
            ignoreWarnings: [
              {
                module: /vscode-languageserver-types[\\/]lib[\\/]umd[\\/]main\.js$/,
                message: /Critical dependency: require function is used/,
              },
            ],
          };
        },
      };
    },
    [
      'content-docs',
      {
        id: 'community',
        path: 'community',
        routeBasePath: 'community',
        editCurrentVersion: false,
        sidebarPath: './sidebarsCommunity.js',
      } satisfies DocsOptions,
    ],
    [
      'content-docs',
      {
        id: 'guides',
        path: 'guides',
        routeBasePath: 'guides',
        editCurrentVersion: false,
        sidebarPath: './sidebarsGuides.js',

        // Guides stay autogenerated so a new one appears just by adding the file. Getting
        // Started is pinned above the divider in sidebarsGuides.js, so drop it here or it
        // would be listed twice.
        sidebarItemsGenerator: async ({ defaultSidebarItemsGenerator, ...args }) => {
          const items = await defaultSidebarItemsGenerator(args);
          return items.filter(
            (item) => !(item.type === 'doc' && GUIDES_PINNED.includes(item.id)),
          );
        },
      } satisfies DocsOptions,
    ],
    [
      'content-docs',
      {
        id: 'whats-new',
        path: 'whats-new',
        routeBasePath: 'whats-new',
        editCurrentVersion: false,
        sidebarPath: './sidebarsWhatsNew.js',

        // The per-plugin highlight reels stay autogenerated, so a new one appears in the
        // sidebar just by adding the file. Changelog and Roadmap are reference pages rather
        // than release notes, so sidebarsWhatsNew.js pins them below a divider instead —
        // drop them here or they would be listed twice.
        sidebarItemsGenerator: async ({ defaultSidebarItemsGenerator, ...args }) => {
          const items = await defaultSidebarItemsGenerator(args);
          return items.filter(
            (item) => !(item.type === 'doc' && WHATS_NEW_PINNED.includes(item.id)),
          );
        },
      } satisfies DocsOptions,
    ],
    [
      "docusaurus-plugin-remote-content",
      {
        name: "changelog",
        sourceBaseUrl: "https://raw.githubusercontent.com/dotBunny/NEXUS/refs/heads/main/",
        outDir: "whats-new",
        documents: ["CHANGELOG.md"],
        modifyContent(filename, content) {
          if (filename.includes("CHANGELOG")) {
            return {
              filename: "changelog.md",
              content: `---
title: Changelog
description: A semantic versioned changelog.
hide_table_of_contents: false
toc_min_heading_level: 2
toc_max_heading_level: 2
---

${content}`
            }
          }
          return undefined
        },
      },
    ]
  ]
};

export default config;
