/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  whatsnew: [
    // Reference pages rather than release notes, so they sit apart from the reels below.
    // There is no index page in this folder: the navbar points straight at the changelog, and
    // the bare /whats-new route forwards there via a redirect in docusaurus.config.ts.
    {
      type: 'doc',
      id: 'changelog',
    },
    {
      type: 'doc',
      id: 'roadmap',
    },
    {
      type: 'html',
      value: '<hr />',
      className: 'sidebar-divider',
    },

    // Per-plugin highlight reels. Autogenerated, so adding `whats-new/<plugin>.md` is all it
    // takes for it to show up here. `WHATS_NEW_PINNED` in docusaurus.config.ts filters the
    // two pages above out of this run so they are not listed twice.
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};
