/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  guide: [
    {
      type: 'doc',
      id: 'getting-started',
    },
    {
      type: 'html',
      value: '<hr />',
      className: 'sidebar-divider',
    },
    {
      type: 'autogenerated',
      dirName: '.',
    }
  ],
};