import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// Overview sits above a divider, with the plugins autogenerated below it. `DOCS_PINNED` in
// docusaurus.config.ts filters it out of the autogenerated run so it is not listed twice —
// that filter applies to every version, so this pin has to be present in each version's
// sidebar (here for current, versioned_sidebars/*.json for the archives) or Overview would
// drop out of that version's sidebar entirely.
const overviewThenPlugins: SidebarsConfig[string] = [
  { type: 'doc', id: 'index' },
  { type: 'html', value: '<hr />', className: 'sidebar-divider' },
  { type: 'autogenerated', dirName: '.' },
];

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  defaultSidebar: overviewThenPlugins,
  docs: overviewThenPlugins,
};

export default sidebars;
